# The AWS Serverless Application Model (SAM) CLI configuration file
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "tacocat-gallery-sam-dev"

[default.validate.parameters]
lint = true

[default.build.parameters]
cached = true
parallel = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[default.deploy.parameters]
s3_prefix = "tacocat-gallery-sam/dev"
resolve_s3 = true
confirm_changeset = true
region = "us-east-1"
image_repositories = []
capabilities = "CAPABILITY_IAM"

[prod]
[prod.global]
[prod.global.parameters]
stack_name = "tacocat-gallery-sam-prod"

[prod.sync]
[prod.sync.parameters]
watch = false

[prod.deploy.parameters]
s3_prefix = "tacocat-gallery-sam/prod"
parameter_overrides = "Environment=prod StageName=prod"