# -----------------------------------------------------------------------------
# Root Stack
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# This is an AWS Serverless Application Model (SAM) template
# It defines the "stack" of AWS resources needed to run the SAM app
# -----------------------------------------------------------------------------
AWSTemplateFormatVersion: '2010-09-09'

# -----------------------------------------------------------------------------
# This file is written in SAM syntax, and gets transfomed and expanded into a  
# CloudFormation template.  The CloudFormation template is what actually gets 
# deployed.  The main point is that SAM syntax is much simpler, with a lot less
# boilerplate around declaring resources like Lambda functions and their 
# accompanying execution roles.
# -----------------------------------------------------------------------------
Transform: AWS::Serverless-2016-10-31

# -----------------------------------------------------------------------------
# This particular template defines the nested stack of stacks that comprise
# the Tacocat photo gallery system
# -----------------------------------------------------------------------------
Description: Tacocat Gallery Root SAM App

# -----------------------------------------------------------------------------
# Resources are the actual assets that will be provisioned on AWS
# -----------------------------------------------------------------------------
Resources:

  # Nested SAM app for the AWS DynamoDB database containing album and image metadata
  Database:
    Type: AWS::Serverless::Application
    Properties:
      Location: db/db_stack.yaml

  # Nested SAM app for AWS API Gateway API to work with images 
  ImageAPI:
    Type: AWS::Serverless::Application
    Properties:
      Location: image_api/image_api_stack.yaml

  # Nested SAM app with the AWS Step Functions image processing state machine
  StateMachine:
    Type: AWS::Serverless::Application
    Properties:
      Location: state_machine/state_machine_stack.yaml

