# -----------------------------------------------------------------------------
# This is an AWS Serverless Application Model (SAM) template
# It defines the "stack" of AWS resources needed to run the SAM app
# -----------------------------------------------------------------------------
AWSTemplateFormatVersion: "2010-09-09"

# -----------------------------------------------------------------------------
# This file is written in SAM syntax, and gets transfomed and expanded into a
# CloudFormation template.  The CloudFormation template is what actually gets
# deployed.  The main point is that SAM syntax is much simpler, with a lot less
# boilerplate around declaring resources like Lambda functions and their
# accompanying execution roles.
# -----------------------------------------------------------------------------
Transform: AWS::Serverless-2016-10-31

# -----------------------------------------------------------------------------
# This particular template defines the back end of the Tacocat photo gallery
# -----------------------------------------------------------------------------
Description: Tacocat Gallery SAM App

# -----------------------------------------------------------------------------
# Parameters that can be specified when deploying this stack
# This is the only way to define constants for use elsewhere in the template
# -----------------------------------------------------------------------------
Parameters:
  CognitoUserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool for Tacocat Gallery Admins
    Default: arn:aws:cognito-idp:us-east-1:010410881828:userpool/us-east-1_DdPFtamLz
  SharpLayerArn:
    Type: String
    Description: ARN of the Lambda Layer containing the Sharp image processing library
    Default: arn:aws:lambda:us-east-1:010410881828:layer:Sharp-0_31_2:1

# -----------------------------------------------------------------------------
# Configuration properties inherited by all resources, such as Lambda functions
# -----------------------------------------------------------------------------
Globals:
  Function:
    Runtime: nodejs18.x
    MemorySize: 256
    Timeout: 100

# -----------------------------------------------------------------------------
# Resources are the actual assets that will be provisioned on AWS
# -----------------------------------------------------------------------------
Resources:
  # -----------------------------------------------------------------------------
  # S3 bucket for original images
  # -----------------------------------------------------------------------------
  OriginalImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-original-images"

  # -----------------------------------------------------------------------------
  # S3 bucket for derived images
  # -----------------------------------------------------------------------------
  DerivedImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-derived-images"

  # -----------------------------------------------------------------------------
  # DynamoDB table containing the album and image metadata
  # -----------------------------------------------------------------------------
  GalleryItemDDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: parentPath
          AttributeType: S
        - AttributeName: itemName
          AttributeType: S
      KeySchema:
        - AttributeName: parentPath
          KeyType: HASH
        - AttributeName: itemName
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
      #StreamSpecification: # enable streaming so that the SearchIndexerFunction lambda can send the stream to be indexed by search engine
      #StreamViewType: "NEW_IMAGE"

  # -----------------------------------------------------------------------------
  # CloudFront CDN distribution that serves the images
  # -----------------------------------------------------------------------------

  # CloudFront distibution
  ImageDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub Distributes the images for ${AWS::StackName}
        Enabled: true
        # Aliases: # Custom domain
        #   - YOUR CNAME HERE # For tacocat.com, must be configured in DreamHost
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Origins:
          - Id: original-images-bucket
            DomainName: !GetAtt OriginalImagesBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginalImagesCloudFrontOriginAccessIdentity}"
        DefaultCacheBehavior:
          TargetOriginId: original-images-bucket
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized managed policy - use this if not using a custom ForwardedValues
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none

  # Allow CloudFront to read from original images bucket
  OriginalImagesBucketCloudFrontReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OriginalImagesBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${OriginalImagesBucket}/*
            Principal:
              CanonicalUser: !GetAtt OriginalImagesCloudFrontOriginAccessIdentity.S3CanonicalUserId

  # CloudFront identity of the original image bucket
  OriginalImagesCloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref OriginalImagesBucket

  # ---------------------------------------------------------------------------
  # Lambda to test resize images
  # It's *NOT* attached to CloudFront in order to...
  # 1) Make it faster to deploy
  # 2) Allow me to turn sourcemap: true
  # ---------------------------------------------------------------------------
  SharpTestImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-SharpTest
      CodeUri: app/src/lambdas/cloudfront/sharpTest/
      Handler: sharpTestLambda.handler
      Environment:
        Variables:
          OriginalImagesBucket: !Ref OriginalImagesBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref OriginalImagesBucket
      Layers:
        - !Ref SharpLayerArn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Sourcemap: true
        Target: "es2020"
        EntryPoints:
          - sharpTestLambda.ts
        External:
          - sharp

  # ---------------------------------------------------------------------------
  # Lambda that gets latest album
  # ---------------------------------------------------------------------------
  GetLatestAlbumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/src/lambdas/api/
      Handler: getLatestAlbumLambda.handler
      Description: API Gateway lambda function that gets the latest album from DynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /latest-album
            Method: GET
            RestApiId: !Ref ImageApi
      Environment:
        Variables:
          GALLERY_ITEM_DDB_TABLE: !Ref GalleryItemDDBTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GalleryItemDDBTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - getLatestAlbumLambda.ts

  # ---------------------------------------------------------------------------
  # Lambda that retrieves album
  # ---------------------------------------------------------------------------
  GetAlbumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/src/lambdas/api/
      Handler: getAlbumLambda.handler
      Description: API Gateway function that returns an album and its children from DynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /album/{albumPath+}
            Method: GET
            RestApiId: !Ref ImageApi
        ApiRootEvent:
          Type: Api
          Properties:
            Path: /album # root album
            Method: GET
            RestApiId: !Ref ImageApi
      Environment:
        Variables:
          GALLERY_ITEM_DDB_TABLE: !Ref GalleryItemDDBTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref GalleryItemDDBTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - getAlbumLambda.ts

  # ---------------------------------------------------------------------------
  # Lambda that creates new album
  # ---------------------------------------------------------------------------
  CreateAlbumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/src/lambdas/api/
      Handler: createAlbumLambda.handler
      Description: API Gateway function that creates a new album in DynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /album/{albumPath+}
            Method: PUT
            RestApiId: !Ref ImageApi
      #           Auth:
      #             Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          GALLERY_ITEM_DDB_TABLE: !Ref GalleryItemDDBTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref GalleryItemDDBTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - createAlbumLambda.ts

  # ---------------------------------------------------------------------------
  # Lambda that updates existing album
  # ---------------------------------------------------------------------------
  UpdateAlbumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/src/lambdas/api/
      Handler: updateAlbumLambda.handler
      Description: API Gateway function that updates an existing album in DynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /album/{albumPath+}
            Method: PATCH
            RestApiId: !Ref ImageApi
      #           Auth:
      #             Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          GALLERY_ITEM_DDB_TABLE: !Ref GalleryItemDDBTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GalleryItemDDBTable
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PartiQLUpdate
              Resource: !GetAtt GalleryItemDDBTable.Arn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - updateAlbumLambda.ts

  # ---------------------------------------------------------------------------
  # Lambda to update existing image
  # ---------------------------------------------------------------------------
  UpdateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/src/lambdas/api/
      Handler: updateImageLambda.handler
      Description: API Gateway function that updates an existing image in DynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /image/{imagePath+}
            Method: PATCH
            RestApiId: !Ref ImageApi
      #            Auth:
      #              Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          GALLERY_ITEM_DDB_TABLE: !Ref GalleryItemDDBTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref GalleryItemDDBTable
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PartiQLUpdate
              Resource: !GetAtt GalleryItemDDBTable.Arn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - updateImageLambda.ts

  # ---------------------------------------------------------------------------
  # Lambda to set album's thumbnail
  # ---------------------------------------------------------------------------
  SetAlbumThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/src/lambdas/api/
      Handler: setAlbumThumbnailLambda.handler
      Description: API Gateway function that sets an album's thumbnail in DynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /album-thumb/{albumPath+}
            Method: PATCH
            RestApiId: !Ref ImageApi
      #            Auth:
      #              Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          GALLERY_ITEM_DDB_TABLE: !Ref GalleryItemDDBTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref GalleryItemDDBTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - setAlbumThumbnailLambda.ts

  # ---------------------------------------------------------------------------
  # Lambda to recut a thumbnail
  # ---------------------------------------------------------------------------
  RecutThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/src/lambdas/api/
      Handler: recutThumbnailLambda.handler
      Description: API Gateway function recuts an album's thumbnail in DynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /thumb/{imagePath+}
            Method: PATCH
            RestApiId: !Ref ImageApi
      #            Auth:
      #              Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          GALLERY_ITEM_DDB_TABLE: !Ref GalleryItemDDBTable
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref GalleryItemDDBTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - recutThumbnailLambda.ts

  # ---------------------------------------------------------------------------
  # Lambda to delete album
  # ---------------------------------------------------------------------------
  DeleteAlbumFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/src/lambdas/api/
      Handler: deleteAlbumLambda.handler
      Description: API Gateway function that deletes an album from DynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /album/{albumPath+}
            Method: DELETE
            RestApiId: !Ref ImageApi
      #            Auth:
      #              Authorizer: CognitoAuthorizer
      Environment:
        Variables:
          GALLERY_ITEM_DDB_TABLE: !Ref GalleryItemDDBTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref GalleryItemDDBTable

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - deleteAlbumLambda.ts

  # ---------------------------------------------------------------------------
  # API Gateway Image API
  # ---------------------------------------------------------------------------
  ImageApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Tacocat Gallery Image API
      StageName: Prod
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn

  # ---------------------------------------------------------------------------
  # Lambda that processes uploaded image, extracts metadata and saves to DyanmoDB
  # ---------------------------------------------------------------------------
  ProcessImageUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/src/lambdas/processImageUpload/
      Handler: processImageUploadLambda.handler
      Description: Lambda that processes images uploaded to S3, extracts metadata and saves to DyanmoDB
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "${AWS::StackName}-original-images"
        - DynamoDBCrudPolicy:
            TableName: !Ref GalleryItemDDBTable
      Events:
        FileUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref OriginalImagesBucket
            Events:
              - "s3:ObjectCreated:*"
      Environment:
        Variables:
          GALLERY_ITEM_DDB_TABLE: !Ref GalleryItemDDBTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - processImageUploadLambda.ts

# -----------------------------------------------------------------------------
# Outputs
# -----------------------------------------------------------------------------
Outputs:
  ImageApi:
    Description: Image API URL - Prod stage
    Value: !Sub https://${ImageApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/

  ImageDomain:
    Description: CloudFront CDN image distribution domain
    Value: !Sub https://${ImageDistribution.DomainName}/
